version: '2'
services:
  mongo:
    image: mongo:3.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  redis:
    image: redis:alpine
  rabbitmq:
    image: rabbitmq:alpine
  postgres-data:
    image: busybox
    volumes:
    - /var/lib/postgresql/data/pgdata        
  postgres:
    image: postgres:alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: heimdall
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: postgres
    volumes_from:
    - postgres-data
    ports:
    - 5432:5432/tcp
  heimdall-api:
    image: getheimdall/heimdall-api:latest
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - HEIMDALL_DATASOURCE_SERVERNAME=postgres
    - HEIMDALL_REDIS_HOST=redis
    - HEIMDALL_MONGO_SERVERNAME=mongo
    - HEIMDALL_MONGO_URL=mongodb://admin:admin@mongo
    - SPRING_RABBITMQ_HOST=rabbitmq
    links:
    - postgres:postgres
    - redis:redis
    - mongo:mongo
    - rabbitmq:rabbitmq
    ports:
    - 9090:9090/tcp        
  heimdall-gateway:
    image: getheimdall/heimdall-gateway:latest
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - HEIMDALL_DATASOURCE_SERVERNAME=postgres
    - HEIMDALL_REDIS_HOST=redis
    - HEIMDALL_MONGO_SERVERNAME=mongo
    - HEIMDALL_MONGO_URL=mongodb://admin:admin@mongo
    - SPRING_RABBITMQ_HOST=rabbitmq
    links:
    - postgres:postgres
    - redis:redis
    - mongo:mongo
    - rabbitmq:rabbitmq
    ports:
    - 8080:8080/tcp        
  heimdall-frontend:
    image: getheimdall/heimdall-frontend:latest   
    environment:
    - REACT_APP_SCHEME=HTTP
    - REACT_APP_ADDRESS=heimdall-api
    - REACT_APP_PORT=9090
    ports:
    - 80:5000/tcp        
