info:
    app:
        profile: developer
        name: "@name@"
        description: "@description@"
        version: "@project.version@"

server:
    context-path: /
    port: 9090

heimdall:
    contextPath: /heimdall/v1
    hostname: hostname
    excludeRabbit: true
    retryable: false
    logstash:
        enabled: true
        destination: 127.0.0.1
    rewrite:
        enable: false
        prefix: heimdall
    redis:
        host: 127.0.0.1
        port: 6379
        maxTotal: 128
        maxIdle: 128
        minIdle: 16
        testOnBorrow: true
        testOnReturn: true
        testWhileIdle: true
        minEvictableIdleTimeSeconds: 60
        timeBetweenEvictionRunsSeconds: 30
        numTestsPerEvictionRun: 3
        blockWhenExhausted: true
        connectionPoolSize: 10
    security:
        enabled: true
        jwt:
            expiration-time: 900000000
            secret: secretKey

spring:
    redis:
        host: 127.0.0.1
        port: 6379
    pid:
        fail-on-write-error: false
        file: heimdall.pid
#    jpa:
#        database-platform: org.hibernate.dialect.PostgreSQLDialect
#        database: POSTGRESQL
#        openInView: false
#        show_sql: true
#        generate-ddl: false
#        hibernate:
#            ddl-auto: none
#            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    jackson:
        serialization:
            INDENT_OUTPUT: true
            WRITE-DATES-AS-TIMESTAMPS: false
    rabbitmq:
        host: 192.168.10.200
        port: 5672
        virtual-host: dev
        requested-heartbeat: 10
    cache:
        type: simple

springfox:
    documentation:
        swagger:
            v2:
                path: /docs

endpoints:
    routes:
        enabled: true
        sensitive: false
    actuator:
        enabled: true
    trace:
        filter:
            enabled: false

management:
    context-path: /manager
    security:
        enabled: false
    health:
        mongo:
            enabled: false
        redis:
            enabled: false
        rabbit:
            enabled: false
        hystrix:
            enabled: false
        refresh:
            enabled: false

zuul:
    filter:
        root: /tmp/interceptors
        interval: 8

security:
    basic:
        enabled: false